import type { LearningCategory } from "@/features/category/types";

export const defaultLearningCategories: LearningCategory[] = [
  {
    id: "leetcode",
    category: "IT",
    category_image: "/images/category/leetcode.png",
    name: "leetcode",
    sort_order: 1,
    created_at: null,
  },
  {
    id: "javascript",
    category: "IT",
    category_image: "/images/category/js.png",
    name: "javascript",
    sort_order: 2,
    created_at: null,
  },
  {
    id: "springboot",
    category: "IT",
    category_image: "/images/category/springboot.png",
    name: "springboot",
    sort_order: 3,
    created_at: null,
  },
  {
    id: "interview question",
    category: "IT",
    category_image: "/images/category/inter_quest.png",
    name: "interview question",
    sort_order: 4,
    created_at: null,
  },
  {
    id: "security",
    category: "IT",
    category_image: "/images/category/security.png",
    name: "security",
    sort_order: 5,
    created_at: null,
  },
  {
    id: "networking",
    category: "IT",
    category_image: "/images/category/net.png",
    name: "networking",
    sort_order: 6,
    created_at: null,
  },
  {
    id: "working issues",
    category: "IT",
    category_image: "/images/category/wk_is.png",
    name: "working issues",
    sort_order: 7,
    created_at: null,
  },
  {
    id: "other",
    category: "Other",
    category_image: "/images/category/other.png",
    name: "other",
    sort_order: 1,
    created_at: null,
  },
];
